### ISSUE TITLE
Implementing in Home Assistant

### ISSUE THREAD

**Issue by Post404** [ThomDietrich/SenseoWifi#41]
Everything in this project has been new for me, soldering, ordering a custom PCB, dealing with firmware. I am now at the point that i'm trying to implement it into Home Assistant. It is connected to the Wifi and to the MQTT broker.
I just don't know how to "translate" the OpenHAB config to Home Assistant. Is there any example available that I can see?

**Comment by ThomDietrich** [comment]
Hey @Post404,
I was happy to read that you were able to bring your Senseo to the point where you can read its status and send commands via MQTT. Correct? Congrats!

Please provide any issue you had or details that was missing from the description. I can certainly add more content to the README of this project.

----

I've also recently hooked my SenseoWifi to HomeAssistant. The current firmware does not support Home Assistant auto discovery via MQTT but that is on my low prio todo list. Till then you can use the following configuration as a starting point:

If you didn't already, activate the [packages concept](https://www.home-assistant.io/docs/configuration/packages/) in Home Assistant's `configuration.yaml` (this is not strictly linked to the below but is imho a must for all HA setups):

```yaml
homeassistant:
  ...
  packages: !include_dir_named packages
```

Now add the following configuration file under `packages/senseo_wifi.yaml`:
```yaml
input_boolean:
  senseowifi_brew_normal:
    name: "SenseoWifi Auslöser einfache Tasse brühen"
    initial: off
    icon: mdi:coffee

  senseowifi_brew_double:
    name: "SenseoWifi Auslöser große Tasse brühen"
    initial: off
    icon: mdi:coffee

switch senseowifi:
  - platform: mqtt
    name: SenseoWifi Power
    #
    state_topic: "homie/senseo-wifi-rf21/machine/power"
    state_on: "true"
    state_off: "false"
    #
    command_topic: "homie/senseo-wifi-rf21/machine/power/set"
    payload_on: "true"
    payload_off: "false"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

sensor senseowifi:
  - platform: mqtt
    name: SenseoWifi Brewed size
    #
    state_topic: "homie/senseo-wifi-rf21/machine/brewedSize"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

  - platform: mqtt
    name: SenseoWifi OpState
    #
    state_topic: "homie/senseo-wifi-rf21/machine/opState"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

binary_sensor:
  - platform: mqtt
    name: SenseoWifi Out-of-water
    #
    state_topic: "homie/senseo-wifi-rf21/machine/outOfWater"
    payload_on: "true"
    payload_off: "false"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

  - platform: mqtt
    name: SenseoWifi Brew
    #
    state_topic: "homie/senseo-wifi-rf21/machine/brew"
    payload_on: "true"
    payload_off: "false"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

  - platform: mqtt
    name: SenseoWifi Cup available
    #
    state_topic: "homie/senseo-wifi-rf21/machine/cupAvailable"
    payload_on: "true"
    payload_off: "false"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

  - platform: mqtt
    name: SenseoWifi Cup full
    #
    state_topic: "homie/senseo-wifi-rf21/machine/cupFull"
    payload_on: "true"
    payload_off: "false"
    #
    availability_topic: "homie/senseo-wifi-rf21/$state"
    payload_available: "ready"
    #value_template: "{{ value }}"

automation:
  - id: "1611257531404"
    alias: Regel SenseoWifi Auslöser normale Tasse brühen
    trigger:
      platform: state
      entity_id: input_boolean.senseowifi_brew_normal
      to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/brew/set"
          payload: "1cup"

  - id: "1611257531405"
    alias: Regel SenseoWifi Auslöser große Tasse brühen
    trigger:
      platform: state
      entity_id: input_boolean.senseowifi_brew_double
      to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/brew/set"
          payload: "2cup"

  - id: "1611257531406"
    alias: Regel SenseoWifi update beim Ausschalten
    trigger:
      platform: state
      entity_id: binary_sensor.senseowifi_brew
      to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.senseowifi_brew_normal
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.senseowifi_brew_double

```

Replace "senseo-wifi-rf21" by whatever your machine is called on the MQTT broker.

Hope that helped. Please provide as much info back as you can
