### ISSUE TITLE
input_boolean for normal size coffee

### ISSUE THREAD

**Issue by luftpumpe83** [ThomDietrich/SenseoWifi#59]
Hi,
finally got it working!
The only problem is that there is no "input.boolean" entity for brewing a normal size cup, just for the double cup.
I also can't find it in senseo_wifi.yaml.
There is also just an automation for a double cup.
Maybe you can add both for a normal cup?
Thank you!

**Comment by Pierre-33** [comment]
It's not an input_boolean but a button. 

From senseo_wifi.yaml:

 ```
button:
    - name: senseowifi_brew_coffee_normal
      unique_id: uniqueid__senseowifi_brew_coffee_normal
      icon: mdi:coffee
      #
      command_topic: "homie/senseo-wifi-rf21/machine/brew/set"
      payload_press: "1cup"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew_coffee_double
      unique_id: uniqueid__senseowifi_brew_coffee_double
      icon: mdi:coffee
      #
      command_topic: "homie/senseo-wifi-rf21/machine/brew/set"
      payload_press: "2cup"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"
```

You can also try the last change list on my fork : https://github.com/Pierre-33/SenseoWifi.git that implement auto discovery for home assistant. It creates all the entities for you (no need of senseo_wifi.yaml anymore, except if you want to keep the automation)
