### ISSUE TITLE
Fix Homeassistant Lovelace configuration

### ISSUE THREAD

**Issue by mboremski** [ThomDietrich/SenseoWifi#66]
Thank you for your project!
More than 2000 coffes have been brewed with this (in openhab).
Now moving it to Homeassistant

I was struggeling while using the readme to implement it into Homeassistant.
These buttons where not working on the dashboard:
![grafik](https://github.com/ThomDietrich/SenseoWifi/assets/13338772/ed03ae12-9b2f-4851-85c1-ab885bf68d3a)

I found that you point to non existing entitys here:
![grafik](https://github.com/ThomDietrich/SenseoWifi/assets/13338772/d6226d4b-12da-40fb-8fb0-10380dc19bc5)

I fixed this by using the buttons defined by `senseo_wifi.yaml` and making them pressable like so:
```yaml
    card:
      type: entities
      entities:
        - type: buttons
          entities:
            - entity: button.senseowifi_brew_coffee_normal
              name: kleine Tasse brühen
              icon: mdi:coffee-to-go
              tap_action:
                action: call-service
                service: button.press
                service_data:
                  entity_id: button.senseowifi_brew_coffee_normal
            - entity: button.senseowifi_brew_coffee_double
              name: große Tasse brühen
              icon: mdi:coffee-to-go
              tap_action:
                action: call-service
                service: button.press
                service_data:
                  entity_id: button.senseowifi_brew_coffee_double
```
Maybe you can update the readme with this.

Could you maybe also give a clear hint to use [packages ](https://www.home-assistant.io/docs/configuration/packages/) to implement `senseo_wifi.yaml`?
As a new homeassistant-user I have been spreading the configs over my `configuration.yaml` befor I found the easy way in #41.
